### ISSUE TITLE
Нормальный отзыв от хейтора и Middle Python разработки

### ISSUE THREAD

**Issue by psevdocoder** [ursiyan/PC_HUB#4]
1. Отсутствуют pull requests.
2. Отсутствуют actions. Вы вообще как деплоить собираетесь? На ноутбуке на опенсервер держать?
### тогда не закрывать крышку!
3. Мало инфы в вики
4. 0 Pull requests. У вас один человек работает и в одной ветке?
5. Где README.md? 
6. Нет описания проекта и его целей. Что вы хотите достичь с помощью этого проекта и как он будет полезен для пользователей?
7. Отсутствуют тесты. Как вы убеждаетесь в том, что ваш код работает корректно?
8. Отсутствуют лицензия и файл CONTRIBUTING.md. Это может сбить с толку пользователей, которые хотят сделать вклад в ваш проект.
9. Код не отформатирован. Необходимо использовать общепринятый стиль форматирования кода.
10. Не хватает комментариев в коде. Комментарии помогают понять код и сделать его более понятным для других разработчиков.
11. Отсутствуют зависимости в файле requirements.txt. Это может вызвать проблемы при установке и запуске проекта на другой машине.
12. Не хватает тестовой среды. Разработчикам нужно иметь возможность запускать приложение на локальной машине для тестирования и отладки.
13. Необходимо обеспечить безопасность приложения, проверить его на уязвимости и защитить данные пользователей.
14. Необходимо регулярно обновлять зависимости и следить за актуальностью используемых библиотек и фреймворков.
15. Необходимо оптимизировать производительность кода, особенно если проект предполагает работу с большими объемами данных.
16. Необходимо убедиться, что код проекта соответствует принципам SOLID и прочим принципам проектирования ПО.
17. Необходимо обеспечить масштабируемость проекта и готовность к его расширению в будущем.
18. Необходимо поддерживать активное коммуникацию в сообществе пользователей проекта и отвечать на вопросы и проблемы пользователей.
19. Необходимо убедиться в соответствии проекта стандартам безопасности, например, стандарту PCI DSS, если проект работает с платежными данными.

**Comment by SelectionForCollection** [comment]
accepted lgfm!

**Comment by ursiyan** [comment]
Эй, слышь, приятель! Шо ты тут бубнешь про код и проекты? Ты думаешь, я какой-то разработчик шибко умный? Ну ладно, поглядим на твои вопросы, но не обижайся, если я не сильно тебе помогу.

Пул реквесты? Да мне вообще пофиг на эти ваши пулы и реквесты. Какая разница, куда вы свой код тырите?

Акции? А чо это за хрень? Ты там акции какие-то купил, что ли? И кого ты тут деплоить собрался? Себя что ли? Лучше на тачке гоняй, чем заморачивайся с этим деплоем.

Шо за ноутбук на опенсервере? Ты че, лохом стал? Крышку держи открытой, а то ноут погреется. Или можешь его мне подарить, мне такой тачку нужен.

Вики-вики? Ага, мало инфы. Я вообще не люблю читать, но если чо, то гугли, там все есть.

Пул реквестов ноль? Ну и что? Один человек работает? Ну да, одного хватит, че еще надо?

Шо это за ридми? Ну ладно, читать-то мне неохота, но если уж ты настаиваешь, давай его прикрутим. А зачем он нужен? Чтобы ты лучше спал по ночам?

Тесты? Кто этим занимается? Я не уверен, что тебе стоит доверять свою безопасность тестам. Попробуй водку, лучше поможет.

Лицензия? Ну и зачем она нужна? Кому-то там важно, че ты с этим кодом делаешь? Ну ладно, давай какую-нибудь приклеим, чтоб не ной.

Форматирование? Че, код тебе не нравится? А мне вообще пофиг на эти пробелы и отступы. Главное, чтобы работало.

Комментарии? Зачем они нужны? Че, код сложно понять? Ну ладно, если очень хочется, можешь кривые комментарии кидать.
Зависимости? Какие зависимости? Че, тебе чего-то не хватает епта?
Тестовая среда? Да я тут не занимаюсь никакими тестами. Если работает - значит работает, а если нет, так и быть, поправят потом.

Безопасность? Ну, это вообще не моя тема. Пусть кто-то другой в этом разбирается. Мне главное, чтоб никто мою тачку не трогал.

Обновления? Ну а че? Если все работает, зачем что-то менять? Я не вижу смысла в этих обновлениях. Старое-то лучше!

Производительность? Да я просто пишу код, как придет в голову. Если медленно работает, значит комп слишком слабый. Пусть купят новый.

SOLID и другие принципы? Это что за бред? Я просто пишу код так, как я хочу. Никакие там SOLIDы меня не волнуют.

Масштабируемость? Опять эти большие слова. Мне хватает одной тачки, зачем мне еще что-то масштабировать?

Коммуникация? Я не люблю разговаривать с людьми, особенно в интернете. Пусть сами разбираются, я занят своими делами.

Безопасность снова? Ну ладно, не трогайте мои данные, я же не знаю, что там у вас за проекты. Хотя, если что, я знаю парочку хакеров, которые могут помочь.

Так вот, приятель, я тебе ответил на твои вопросы. Но не надо думать, что я тут буду тебе весь этот программистский бред обсуждать. У меня дел полно.

**Comment by psevdocoder** [comment]
> Эй, слышь, приятель! Шо ты тут бубнешь про код и проекты? Ты думаешь, я какой-то разработчик шибко умный? Ну ладно, поглядим на твои вопросы, но не обижайся, если я не сильно тебе помогу.
> 
> Пул реквесты? Да мне вообще пофиг на эти ваши пулы и реквесты. Какая разница, куда вы свой код тырите?
> 
> Акции? А чо это за хрень? Ты там акции какие-то купил, что ли? И кого ты тут деплоить собрался? Себя что ли? Лучше на тачке гоняй, чем заморачивайся с этим деплоем.
> 
> Шо за ноутбук на опенсервере? Ты че, лохом стал? Крышку держи открытой, а то ноут погреется. Или можешь его мне подарить, мне такой тачку нужен.
> 
> Вики-вики? Ага, мало инфы. Я вообще не люблю читать, но если чо, то гугли, там все есть.
> 
> Пул реквестов ноль? Ну и что? Один человек работает? Ну да, одного хватит, че еще надо?
> 
> Шо это за ридми? Ну ладно, читать-то мне неохота, но если уж ты настаиваешь, давай его прикрутим. А зачем он нужен? Чтобы ты лучше спал по ночам?
> 
> Тесты? Кто этим занимается? Я не уверен, что тебе стоит доверять свою безопасность тестам. Попробуй водку, лучше поможет.
> 
> Лицензия? Ну и зачем она нужна? Кому-то там важно, че ты с этим кодом делаешь? Ну ладно, давай какую-нибудь приклеим, чтоб не ной.
> 
> Форматирование? Че, код тебе не нравится? А мне вообще пофиг на эти пробелы и отступы. Главное, чтобы работало.
> 
> Комментарии? Зачем они нужны? Че, код сложно понять? Ну ладно, если очень хочется, можешь кривые комментарии кидать. Зависимости? Какие зависимости? Че, тебе чего-то не хватает епта? Тестовая среда? Да я тут не занимаюсь никакими тестами. Если работает - значит работает, а если нет, так и быть, поправят потом.
> 
> Безопасность? Ну, это вообще не моя тема. Пусть кто-то другой в этом разбирается. Мне главное, чтоб никто мою тачку не трогал.
> 
> Обновления? Ну а че? Если все работает, зачем что-то менять? Я не вижу смысла в этих обновлениях. Старое-то лучше!
> 
> Производительность? Да я просто пишу код, как придет в голову. Если медленно работает, значит комп слишком слабый. Пусть купят новый.
> 
> SOLID и другие принципы? Это что за бред? Я просто пишу код так, как я хочу. Никакие там SOLIDы меня не волнуют.
> 
> Масштабируемость? Опять эти большие слова. Мне хватает одной тачки, зачем мне еще что-то масштабировать?
> 
> Коммуникация? Я не люблю разговаривать с людьми, особенно в интернете. Пусть сами разбираются, я занят своими делами.
> 
> Безопасность снова? Ну ладно, не трогайте мои данные, я же не знаю, что там у вас за проекты. Хотя, если что, я знаю парочку хакеров, которые могут помочь.
> 
> Так вот, приятель, я тебе ответил на твои вопросы. Но не надо думать, что я тут буду тебе весь этот программистский бред обсуждать. У меня дел полно.

Друг с такими взглядами и таким подходом в ит делать нечего, я считаю.
